#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';

use Admingraph::JSON;
our (%lang, $html);
our ($admin, $db, %conf)

my $district_connection = JSON->connection_district($admin, $db, \%conf);

1;
